#! /bin/sh
# /etc/init.d/mailhog
#
# MailHog init script.
#
# @author Jeff Geerling

### BEGIN INIT INFO
# Provides:          mailhog
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start MailHog at boot time.
# Description:       Enable MailHog.
### END INIT INFO

PID=/run/mailhog.pid
LOCK=/var/lock/mailhog.lock
USER=nobody
BIN=/usr/local/bin/mailhog
DAEMONIZE_BIN=/usr/bin/daemonize

# Carry out specific functions when asked to by the system
case "$1" in
  start)
    printf '%s\n' "Starting mailhog."
    $DAEMONIZE_BIN -p $PID -l $LOCK -u $USER $BIN -hostname mail.localhost
    # $DAEMONIZE_BIN -p $PID -l $LOCK -u $USER $BIN -hostname mail.localhost -storage maildir -maildir-path /home/am/Maildir
    ;;
  stop)
    if [ -f $PID ]; then
      printf '%s\n' "Stopping mailhog.";
      kill -TERM $(cat $PID);
      rm -f $PID;
    else
      printf '%s\n' "MailHog is not running.";
    fi
    ;;
  restart)
    printf '%s\n' "Restarting mailhog."
    if [ -f $PID ]; then
      kill -TERM $(cat $PID);
      rm -f $PID;
    fi
    $DAEMONIZE_BIN -p $PID -l $LOCK -u $USER $BIN
    ;;
  status)
    if [ -f $PID ]; then
      printf '%s\n' "MailHog is running.";
    else
      printf '%s\n' "MailHog is not running.";
      exit 3
    fi
    ;;
  *)
    printf '%s\n' "Usage: /etc/init.d/mailhog {start|stop|status|restart}"
    exit 1
    ;;
esac

exit 0