#!/bin/bash
# set -x

echo
echo '               DEBIAN SETUP WEB                             '
echo '               ----------------                             '
echo '  This will setup basic shell environment and install php   '
echo '  MariaDB and nginx to create a web server.                 '
echo

MARIADB_VERSION='10.7'
PHP_VERSION='8.0'

if [[ $EUID -eq 0 ]]; then
    tput setaf 1;
    echo "! Please launch as a user belonging to sudo group, and not as root. !"
    exit 1
else
    SUDO=sudo
fi

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )

echo
echo "Select / unselect options to install:"
echo

source $SCRIPT_DIR/misc/multiselect
INSTALL_OPTIONS=("Shell setup" "MariaDB ${MARIADB_VERSION}" "PHP ${PHP_VERSION}" "NginX" )
PRE_SELECTIONS=("true" "true" "true" "true")
multiselect SELECTION INSTALL_OPTIONS PRE_SELECTIONS

if [ ${SELECTION[0]} = "true" ]; then
    echo
    echo "Configuring system (shell utils etc.)"
    echo "-------------------------------------"
    read -p "Press enter to continue"
    source $SCRIPT_DIR/setup.d/_system
fi

if [ ${SELECTION[1]} = "true" ]; then
    echo
    echo "Installing and configuring MariaDB ${MARIADB_VERSION}"
    echo "---------------------------------------"
    read -p "Press enter to continue"
    source $SCRIPT_DIR/setup.d/_mariadb
fi

if [ ${SELECTION[2]} = "true" ]; then
    echo
    echo "Installing and configuring PHP ${PHP_VERSION}"
    echo "----------------------------------"
    read -p "Press enter to continue"
    source $SCRIPT_DIR/setup.d/_php
fi

if [ ${SELECTION[3]} = "true" ]; then
    echo
    echo "Installing and configuring latest NginX"
    echo "---------------------------------------"
    read -p "Press enter to continue"
    source $SCRIPT_DIR/setup.d/_nginx
fi

echo
echo "Restarting services ..."
[ ${SELECTION[1]} = true ] && ${SUDO} systemctl restart mariadb
[ ${SELECTION[2]} = true ] && ${SUDO} systemctl restart php${PHP_VERSION}-fpm
[ ${SELECTION[3]} = true ] && ${SUDO} systemctl restart nginx

echo
echo 'Setup completed!'
echo '----------------------------------------------------------------'
echo 'reload ~/.profile to refresh shell.'
echo 'run zsh to laucnch zsh shell or chsh to switch to zsh.'
echo 'run setup_mailhog to install a mail catcher'
echo 'run setup_sama to install samba'
echo 'run setup_lego to install letsencrypt client'
echo
echo 'Consider adding mysql superuser for web based administration:'
echo "sudo mysql -e \"CREATE USER ${USER}@'%' IDENTIFIED VIA" 
echo "mysql_native_password AS PASSWORD('password') OR unix_socket;"
echo "GRANT ALL PRIVILEGES ON *.* TO $USER@'%' WITH GRANT OPTION;\""
echo '----------------------------------------------------------------'
echo