#!/bin/sh
# set -x

if [ "$(whoami)" != "root" ]; then
	SUDO=sudo
fi

setup_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)

${SUDO} apt -y install samba

${SUDO} cp -bv $setup_dir/root/etc/samba/* /etc/samba/

cat <<-EOF

	Edit /etc/samba/smb.conf for user names and shares
	Add users with: smbpasswd -a $USER
	Restart nmbd and smbd services
	EOF
