#!/bin/bash
# set -x

if [ "$(whoami)" != "root" ]; then
  SUDO=sudo
fi

echo -e "\nInstalling composer ..."
if command -v php &> /dev/null
then
  EXPECTED_CHECKSUM="$(php -r 'copy("https://composer.github.io/installer.sig", "php://stdout");')"
  php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
  php -r "if (hash_file('sha384', 'composer-setup.php') === '${EXPECTED_CHECKSUM}') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;"
  ${SUDO} php composer-setup.php --filename=composer --install-dir=/usr/local/bin
  php -r "unlink('composer-setup.php');"
else
  echo "php not installed."
fi

echo -e '\nInstalling drush ...'
wget https://github.com/drush-ops/drush/releases/download/8.4.11/drush.phar
mv drush.phar drush
chmod +x drush
${SUDO} mv drush /usr/local/bin

echo -e '\nInstalling cv ...'
${SUDO} curl -LsS https://download.civicrm.org/cv/cv.phar -o /usr/local/bin/cv
${SUDO} chmod +x /usr/local/bin/cv

echo -e '\nInstalling cv ...'
${SUDO} curl -LsS https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar -o /usr/local/bin/wp
${SUDO} chmod +x /usr/local/bin/wp
wp --info
