#!/bin/bash
# set -x

setup_dir=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
debian_release=$(lsb_release -sc)
userid=$(id -u)
mariadb_ver='11.4'
php_ver='8.3'

if grep -i microsoft /proc/version; then
  is_wsl=true
else
  is_wsl=false
fi

if [ "$(id -u)" -eq 0 ]; then
    msg=$(printf "Launch as a sudo user to setup environment and utilities.\nContinue as root?")
    if (whiptail --title "Running as root user" --yesno "$msg" --defaultno 0 0 3>&2 2>&1 1>&3); then
        echo "You have selected to run as root"
        printf "Press enter to continue"
        read key
    else
        echo "Relaunch as sudo user"
        exit
    fi
else
    SUDO=sudo
    ${SUDO} echo
fi

. $setup_dir/misc/utils.sh

msg=$(printf "This will setup basic web servers\nSelect what to install:")
selection=$(
whiptail --title "Debian Web Server Setup" --checklist \
"$msg" 8 0 0 \
Shell "Setup user shell environment and utilities" 1 \
MariaDB "Install MariaDb $mariadb_ver" 0 \
Nginx "Install latest Nginx" 0 \
PHP "Install php $php_ver" 0 \
3>&2 2>&1 1>&3
);

exitstatus=$?
if [ $exitstatus != 0 ] || [ "x$selection" = "x" ]; then
    echo "Nothing selected!"
    exit
fi

if instr "Shell" "$selection"; then
    echo "---"
    echo "Continue with shell setup ..."
    printf "Press enter to continue"
    read key
    . $setup_dir/setup.d/_shell.sh
fi

if instr "PHP" "$selection"; then
    echo "---"
    echo "Continue with installing PHP ${php_ver}"
    printf "Press enter to continue"
    read key
    . $setup_dir/setup.d/_php.sh
fi

if instr "Nginx" "$selection"; then
    echo "---"
    echo "Continue with installing Nginx"
    printf "Press enter to continue"
    read key
    . $setup_dir/setup.d/_nginx.sh
fi

if instr "MariaDB" "$selection"; then
    echo "---"
    echo "Continue with installing MariaDB ${mariadb_ver} ..."
    printf "Press enter to continue"
    read key
    . $setup_dir/setup.d/_mariadb.sh
fi


echo
echo "Restarting services ..."
instr "MariaDB" "$selection" && echo "mariadb" && ${SUDO} systemctl restart mariadb
instr "Nginx" "$selection" && echo "nginx" && ${SUDO} systemctl restart nginx
instr "PHP" "$selection" && echo "php${php_ver}-fpm" && ${SUDO} systemctl restart php${php_ver}-fpm

# Final message
cat <<_END_

Setup completed!'
----------------'
. ~/.profile to reload bash config.
run setup_webutils to install website maintenance utils.
run get-utils mailpit to install a local mail catcher
run setup_samba to install samba
----------------

_END_
