#!/bin/bash
# set -x

MARIADB_VERSION='10.7'
PHP_VERSION='8.0'

if [[ $EUID -eq 0 ]]; then
    echo "Do not run as root! Launch as a user belonging to sudo group."
    exit 1
else
    SUDO=sudo
fi

echo '**********************************************************'
echo '*               DEBIAN SERVER SETUP                      *'
echo '**********************************************************'
echo '*                                                        *'
echo '*  This script will setup basic shell environment and    *'
echo '*  install MariaDB, php and nginx.                       *'
echo '*                                                        *'
echo '*  Before running this script, make sure sudo and curl   *'
echo '*  are installed.                                        *'
echo '*                                                        *'
echo '*  Sign in as root then type:                            *'
echo '*  > apt update && apt install curl sudo                 *'
echo '*                                                        *'
echo '*  Then add primary user account to sudo group           *'
echo '*  > usermod -a -G sudo username                         *'
echo '*                                                        *'
echo '*  Sign in again to the user account then run this       *'
echo '*  script.                                               *'
echo '*                                                        *'
echo '**********************************************************'

while true
do
	read -p "Continue (y/n)? " choice
	case "$choice" in
    y|Y )   echo
            echo "Select / unselect options to install:"
            echo
		    break;;
    n|N )   exit
			break;;
    * )     echo "invalid";;
	esac
done

SCRIPT_DIR=$( cd -- "$( dirname -- "${BASH_SOURCE[0]}" )" &> /dev/null && pwd )


source $SCRIPT_DIR/misc/multiselect
INSTALL_OPTIONS=("Shell setup" "MariaDB ${MARIADB_VERSION}" "PHP ${PHP_VERSION}" "NginX" )
PRE_SELECTIONS=("true" "true" "true" "true")
multiselect SELECTION INSTALL_OPTIONS PRE_SELECTIONS

if [ ${SELECTION[0]} = "true" ]; then
    echo
    echo "Configuring system (shell utils etc.)"
    echo "-------------------------------------"
    read -p "Press enter to continue"
    # source $SCRIPT_DIR/setup.d/_system
fi

if [ ${SELECTION[1]} = "true" ]; then
    echo
    echo "Installing and configuring MariaDB ${MARIADB_VERSION}"
    echo "---------------------------------------"
    read -p "Press enter to continue"
    # source $SCRIPT_DIR/setup.d/_mariadb
fi

if [ ${SELECTION[2]} = "true" ]; then
    echo
    echo "Installing and configuring PHP ${PHP_VERSION}"
    echo "----------------------------------"
    read -p "Press enter to continue"
    # source $SCRIPT_DIR/setup.d/_php
fi

if [ ${SELECTION[3]} = "true" ]; then
    echo
    echo "Installing and configuring latest NginX"
    echo "---------------------------------------"
    read -p "Press enter to continue"
    # source $SCRIPT_DIR/setup.d/_nginx
fi

echo
echo "Restarting services ..."
[ ${SELECTION[1]} = true ] && ${SUDO} systemctl restart mariadb
[ ${SELECTION[2]} = true ] && ${SUDO} systemctl restart php${PHP_VERSION}-fpm
[ ${SELECTION[3]} = true ] && ${SUDO} systemctl restart nginx

echo
echo 'reload ~/.profile to refresh shell.'
echo 'run zsh to laucnch zsh shell or chsh to switch to zsh.'
echo 'run setup_mailhog to install a mail catcher'
echo 'run setup_sama to install samba'
echo 'run setup_lego to install letsencrypt client'
echo
